version: "3"

services:
  test-env:
    build:
      args:
        JFROG_USERNAME: $JFROG_USERNAME
        JFROG_PASSWORD: $JFROG_PASSWORD
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/repo
      - ./results:/tmp/results
      - ./logs:/tmp/logs
    container_name: test-env
    entrypoint:
      - /bin/bash
      - -l
      - -c
    command:
      - tail -f /dev/null

