name: CI on Merge

on:
 push:
   branches:
     - main

env:
  APP_NAME: auto-morpheus-bmaas
  version: "8.0.5.localdev${GITHUB_RUN_NUMBER}"
  JFROG_USERNAME: ${{ secrets.CCS_JFROG_USERNAME }}
  JFROG_PASSWORD: ${{ secrets.CCS_JFROG_PASSWORD }}

jobs:
  BUILD_PUBLISH:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        shell: bash
        run: |
          cat /etc/os-release
          sudo apt-get update
          sudo apt-get -y dist-upgrade
          sudo apt-get install --no-install-recommends --no-install-suggests -y curl libpq-dev build-essential python3 python3-dev python3-pip python3-setuptools python3-venv
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip
          pip install poetry
          poetry config http-basic.jfrog "${JFROG_USERNAME}" "${JFROG_PASSWORD}"
          poetry install
          pip install sphinx sphinx-rtd-theme sphinx-autoapi

      - name: Build Sphinx Docs
        run: |
          source .venv/bin/activate
          sphinx-apidoc -f -e -o docs/source auto-morpheus-bmaas/
          make -C docs clean
          make -C docs html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html