name: CI on PR

on: [pull_request]

env:
  APP_NAME: hpe-morpheus-automation-libs
  gh_token: ${{ secrets.GLCP_GH_TOKEN }}
  jira_user: ${{ secrets.CCS_JIRA_USER }}
  jira_apikey: ${{ secrets.CCS_JIRA_APIKEY }}

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate PR Title
      shell: bash
      run: |
        ls
        cd $GITHUB_WORKSPACE
        export PR_TITLE="${{ github.event.pull_request.title }}"
        export jira_user=${{ env.jira_user }}
        export jira_apikey=${{ env.jira_apikey }}
        chmod +x scripts/pr_title_validation.py
        python scripts/pr_title_validation.py -p "${PR_TITLE}" -u "${jira_user}" -a "${jira_apikey}"

    - name: Lint
      shell: bash
      run: |
          cd $GITHUB_WORKSPACE
          pip install mypy==1.8.0 autoflake==2.2.1 flake8==7.1.2 black==24.4.2 isort==5.13.2
          chmod +x ./scripts/linters.sh
          scripts/linters.sh

    - name: doc-string verification
      shell: bash
      run: |
          cd $GITHUB_WORKSPACE
          pip install pydocstyle
          chmod +x ./scripts/docstring_validation.sh
          scripts/docstring_validation.sh